Use fewer testbeds

diff --git a/debian/tests/web b/debian/tests/web
--- a/debian/tests/web
+++ b/debian/tests/web
@@ -1,15 +1,21 @@
-#!/bin/sh
+#!/bin/bash
 set -e
 
+rc=0
 check() {
+    local url contains page
     url=$1
     contains=$2
     page=$(curl -sSL "$url")
-    printf "%s" "$page" | grep -q "$contains" || {
+    if printf "%s" "$page" | grep -q "$contains"; then
+        printf '%s contains "%s", good!\n' "$url" "$contains"
+    else
         printf '%s did not contain "%s"!\n' "$url" "$contains" 1>&2
-        printf '======== %s\n%s\n--------\n' "$url" "$page"
-        return 1
-    }
+        printf '======== %s\n' "$url"
+        printf '%s' "$page" | head -n 10
+        printf '\n--------\n'
+        rc=1
+    fi
 }
 
 set -x
@@ -24,11 +30,17 @@ hostname=$(hostname -f)
 a2ensite "$hostname.conf"
 a2dissite 000-default
 a2query -s
-service apache2 reload
-auth=test:testpwd
-check http://"$auth@$hostname"/          "This is the MOTD"
-check http://"$auth@$hostname"/info      "Last updated"
-check http://"$auth@$hostname"/changelog "This is the changelog"
-check http://"$auth@$hostname"/stats     "Server stats"
-check http://"$auth@$hostname"/ports     "Open TCP"
-check http://"$auth@$hostname"/du        "Disk Usage"
+# NB: a2enmod cgid requires an apache restart
+service apache2 restart
+service apache2 status
+url=http://test:testpwd@localhost
+set +x
+check "$url"/          "This is the MOTD"
+check "$url"/info      "Last updated"
+check "$url"/changelog "This is the changelog"
+check "$url"/stats     "Server stats"
+check "$url"/ports     "Open TCP"
+check "$url"/du        "Disk Usage"
+tail /var/log/apache2/error.log
+tail /var/log/apache2/"$hostname"/error.log
+exit $rc
